POST http://localhost:3000/api/v1/links
Content-Type: application/json

{
    "code": "teste2",
    "url": "https://rocketseat.com.br"
}

###

GET http://localhost:3000/api/v1/links

###

GET http://localhost:3000/rocketseat

###

GET http://localhost:3000/api/v1/metrics

